import { useEffect, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowLeft, ArrowRight, Boxes, ClipboardCheck, ClipboardList, Factory, Layers3,  Menu, Plus, Settings2, Wrench } from 'lucide-react';
import { api, date, orderStatus, planStatus, reportStatus, roleName } from './api';
import type { Bom, Dashboard, Order, Page, Plan, Report, Session, User } from './api';
import { BomDetail, BomsPage } from './BomPage';
import { MaterialPicker, MaterialsPage } from './MaterialPage';
import { AiAssistant } from './AiAssistant';
import { SettingsPage } from './SettingsPage';
import './shell-polish.css';
import './dashboard.css';
import { AccountDock } from './AccountDock';
import { MemberAdmin } from './MemberAdmin';

function useLoad<T>(path: string | null, deps: unknown[] = []) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [tick, setTick] = useState(0);
  useEffect(() => { let active = true; if (!path) { setLoading(false); return; } setLoading(true); api<T>(path).then(value => { if (active) { setData(value); setError(''); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [path, tick, ...deps]);
  return { data, error, loading, reload: () => setTick(n => n + 1) };
}
function useAction(done?: () => void) { const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false); async function run<T>(path: string, body?: unknown) { setBusy(true); setError(''); setSuccess(''); try { const value = await api<T>(path, body); setSuccess('操作成功'); done?.(); return value; } catch (e) { setError(e instanceof Error ? e.message : '操作失败'); return null; } finally { setBusy(false); } } return { run, error, success, busy }; }
function Notice({ error, success }: { error?: string; success?: string }) { return <>{error && <div className="notice error" role="alert">{error}</div>}{success && <div className="notice success" role="status">{success}</div>}</>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [close]); return <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-button" onClick={close} aria-label="关闭">×</button></div>{children}</div></div>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function Header({ title, subtitle, action, back }: { title: string; subtitle?: string; action?: ReactNode; back?: string }) { return <div className="page-head"><div className="page-heading">{back && <Link className="back" to={back}><ArrowLeft size={18}/></Link>}<div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div></div>{action}</div>; }
function Pager({ page, total, change }: { page: number; total: number; change: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / 20)); return pages > 1 ? <div className="pager"><button className="button secondary" disabled={page <= 1} onClick={() => change(page - 1)}>上一页</button><span>第 {page} / {pages} 页 · 共 {total} 条</span><button className="button secondary" disabled={page >= pages} onClick={() => change(page + 1)}>下一页</button></div> : null; }
function Progress({ done, total }: { done: number; total: number }) { const pct = total ? Math.min(100, Math.round(done / total * 100)) : 0; return <div className="progress-wrap"><div className="progress"><span style={{ width: `${pct}%` }}/></div><small>{done} / {total} 合格 · {pct}%</small></div>; }

export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [ready, setReady] = useState(false);
  useEffect(() => { api<Session>('/me').then(setSession).catch(() => {}).finally(() => setReady(true)); }, []);
  if (!ready) return <div className="screen-center">正在加载…</div>;
  if (!session) return <Login done={setSession}/>;
  return <BrowserRouter><Shell session={session} logout={() => setSession(null)}/></BrowserRouter>;
}
function Login({ done }: { done: (s: Session) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const action = useAction();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await action.run<Session>('/auth/login', { email, password }); if (value) { const me = await api<Session>('/me'); done(me); } }
  return <div className="login-screen"><div className="login-card"><div className="brand"><div className="brand-mark"><Factory size={25}/></div><div><strong>电子制造 MES</strong><span>车间执行系统</span></div></div><h1>欢迎回来</h1><p>计划、工单与报工集中管理</p><form onSubmit={submit}><Field label="邮箱"><input type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required/></Field><Field label="密码"><input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required/></Field><Notice error={action.error}/><button className="button primary full" disabled={action.busy}>登录</button></form></div></div>;
}
const nav = [{ to: '/', label: '工作台', icon: Activity }, { to: '/materials', label: '物料档案', icon: Boxes }, { to: '/boms', label: '物料清单 BOM', icon: Layers3 }, { to: '/plans', label: '生产计划', icon: ClipboardList }, { to: '/orders', label: '工单', icon: Wrench }, { to: '/reviews', label: '报工审核', icon: ClipboardCheck }, { to: '/admin', label: '成员管理', icon: Settings2 }];
function Shell({ session, logout }: { session: Session; logout: () => void }) {
  const [menu, setMenu] = useState(false);
  useEffect(() => { if (!menu) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenu(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [menu]);
  async function signOut() { await api('/auth/logout', {}); logout(); }
  return <div className="app-shell"><aside className={menu ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><Factory size={22}/></div><div><strong>电子制造 MES</strong><span>车间执行系统</span></div></div><nav>{nav.filter(n => (n.to !== '/reviews' || ['admin','supervisor'].includes(session.user.role)) && (!['/boms','/materials'].includes(n.to) || session.user.role !== 'operator') && (n.to !== '/admin' || session.user.role === 'admin')).map(n => <NavLink key={n.to} to={n.to} end={n.to === '/'} onClick={() => setMenu(false)} className={({ isActive }) => isActive ? 'active' : ''}><n.icon size={18}/>{n.label}</NavLink>)}</nav><AccountDock name={session.user.name} email={session.user.email} role={roleName[session.user.role]} onLogout={signOut}/></aside>{menu && <button type="button" className="mobile-scrim" aria-label="关闭导航" onClick={() => setMenu(false)}/>}<div className="main-shell"><header className="topbar"><button className="menu-button" onClick={() => setMenu(!menu)} aria-label={menu ? "关闭导航" : "打开导航"} aria-expanded={menu}><Menu size={20}/></button></header><main><Routes><Route path="/" element={<DashboardPage session={session}/>}/><Route path="/materials" element={<MaterialsPage session={session}/>}/><Route path="/boms" element={<BomsPage session={session}/>}/><Route path="/boms/:id" element={<BomDetail session={session}/>}/><Route path="/plans" element={<PlansPage session={session}/>}/><Route path="/plans/:id" element={<PlanDetail session={session}/>}/><Route path="/orders" element={<OrdersPage/>}/><Route path="/orders/:id" element={<OrderDetail session={session}/>}/><Route path="/reviews" element={<ReviewsPage/>}/><Route path="/admin" element={<MemberAdmin session={session}/>}/><Route path="/settings" element={<SettingsPage name={session.user.name} email={session.user.email} role={roleName[session.user.role]} isAdmin={session.user.role === 'admin'}/>}/><Route path="/settings/ai" element={session.user.role === 'admin' ? <SettingsPage name={session.user.name} email={session.user.email} role={roleName[session.user.role]} isAdmin/> : <Navigate to="/settings"/>}/><Route path="*" element={<div className="panel"><h1>页面不存在</h1><p className="muted">请从导航选择要查看的业务页面。</p><Link className="button primary" to="/">返回工作台</Link></div>}/></Routes></main></div><AiAssistant variant="mes"/></div>;
}
function DashboardPage({ session }: { session: Session }) {
  const { data, error, loading } = useLoad<Dashboard>('/dashboard');
  const plans = useLoad<Page<Plan>>('/plans?page=1&page_size=4');
  const orders = useLoad<Page<Order>>('/orders?page=1&page_size=4');
  const canReview = ['admin', 'supervisor'].includes(session.user.role);
  const canPlan = ['admin', 'planner'].includes(session.user.role);
  return <div className="mes-dashboard">
    <Header title="工作台" subtitle="生产进度与待处理事项"/>
    <Notice error={error}/>
    {loading && !data ? <div className="loading">正在加载…</div> : data && <>
      <div className="stat-grid">
        <Link to="/plans" className="stat-card"><span>进行中的计划</span><strong>{data.active_plans}</strong><small>查看生产计划</small><ArrowRight size={18}/></Link>
        <Link to="/orders" className="stat-card"><span>待完成工单</span><strong>{data.active_orders}</strong><small>{session.user.role === 'operator' ? '查看我的工单' : '查看全部工单'}</small><ArrowRight size={18}/></Link>
        {canReview ? <Link to="/reviews" className="stat-card"><span>待审核报工</span><strong>{data.pending_reports}</strong><small>前往审核</small><ArrowRight size={18}/></Link> : <div className="stat-card"><span>{session.user.role === 'operator' ? '我提交的待审核报工' : '待审核报工'}</span><strong>{data.pending_reports}</strong><small>审核后计入产量</small></div>}
      </div>
      <div className="mes-dashboard-grid">
        <section className="panel mes-progress-panel"><div className="mes-panel-head"><h2>生产进度</h2><span>当前可查看工单</span></div><div className="big-number">{data.good_qty}<span> / {data.target_qty} 件合格</span></div><Progress done={data.good_qty} total={data.target_qty}/><div className="mes-progress-facts"><div><span>已审核不良</span><strong>{data.defect_qty} 件</strong></div><div><span>合格完成率</span><strong>{data.target_qty ? Math.min(100, Math.round(data.good_qty / data.target_qty * 100)) : 0}%</strong></div></div><p className="muted">{data.definition}</p></section>
        <section className="panel mes-orders-panel"><div className="mes-panel-head"><h2>近期工单</h2><Link to="/orders">全部工单 <ArrowRight size={15}/></Link></div><Notice error={orders.error}/>{orders.loading && !orders.data ? <div className="loading">正在加载…</div> : orders.data?.items.length ? <div className="mes-recent-list">{orders.data.items.map(order => <Link to={`/orders/${order.id}`} key={order.id}><span><strong>{order.code} · {order.operation}</strong><small>{order.plan?.product || '未关联产品'} · 合格 {order.goodQty}/{order.targetQty} 件</small></span><span className={`badge ${order.status}`}>{orderStatus[order.status] || order.status}</span></Link>)}</div> : <div className="mes-dashboard-empty">暂无工单<Link to="/orders">查看工单列表</Link></div>}</section>
      </div>
    </>}
    <section className="panel mes-plans-panel"><div className="mes-panel-head"><h2>近期计划</h2><Link to="/plans">全部计划 <ArrowRight size={15}/></Link></div><Notice error={plans.error}/>{plans.loading && !plans.data ? <div className="loading">正在加载…</div> : plans.data?.items.length ? <div className="mes-recent-list">{plans.data.items.map(plan => <Link to={`/plans/${plan.id}`} key={plan.id}><span><strong>{plan.code} · {plan.product}</strong><small>目标 {plan.targetQty} 件 · 截止 {date(plan.dueAt)}</small></span><span className={`badge ${plan.status}`}>{planStatus[plan.status] || plan.status}</span></Link>)}</div> : <div className="mes-dashboard-empty">暂无计划{canPlan && <Link to="/plans">前往创建计划</Link>}</div>}</section>
  </div>;
}
function PlansPage({ session }: { session: Session }) {
  const navigate = useNavigate(); const [page,setPage] = useState(1); const { data, error, loading, reload } = useLoad<Page<Plan>>(`/plans?page=${page}`); const [create, setCreate] = useState(false);
  return <><Header title="生产计划" action={['admin','planner'].includes(session.user.role) && <button className="button primary" onClick={() => setCreate(true)}><Plus size={17}/>新建计划</button>}/><section className="panel"><Notice error={error}/>{loading && !data ? <div className="loading">正在加载…</div> : data?.items.length ? <div className="record-list">{data.items.map(p => <Link to={`/plans/${p.id}`} key={p.id} className="record"><div><strong>{p.code} · {p.product}</strong><span>SKU {p.productSku} · 计划 {p.targetQty} 件 · 截止 {date(p.dueAt)}</span></div><span className={`badge ${p.status}`}>{planStatus[p.status]}</span><ArrowRight size={17}/></Link>)}</div> : <Empty text="暂无生产计划"/>}</section><Pager page={page} total={data?.total || 0} change={setPage}/>{create && <CreatePlan close={() => setCreate(false)} done={id => { setCreate(false); reload(); navigate(`/plans/${id}`); }}/>}</>;
}
function CreatePlan({ close, done }: { close: () => void; done: (id: string) => void }) {
  const [code, setCode] = useState(''); const [product, setProduct] = useState(''); const [sku, setSku] = useState(''); const [productId, setProductId] = useState(''); const [qty, setQty] = useState(''); const [due, setDue] = useState(''); const [note, setNote] = useState(''); const [bomId, setBomId] = useState(''); const boms = useLoad<Bom[]>('/boms'); const action = useAction();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await action.run<Plan>('/plans', { code, product_material_id: productId, bom_id: bomId || undefined, target_qty: Number(qty), due_at: new Date(due).toISOString(), note }); if (value) done(value.id); }
  const released = boms.data?.filter(b => b.status === 'released') || [];
  return <Modal title="新建生产计划" close={close}><form className="form" onSubmit={submit}><div className="field"><span>生产产品</span><MaterialPicker label="生产产品" manufactured value={productId} selectedText={`${sku} · ${product}`} onChange={material => { setProductId(material?.id || ''); setProduct(material?.name || ''); setSku(material?.sku || ''); setBomId(''); }}/></div><Field label="已发布 BOM（可选）"><select value={bomId} onChange={e => { const selected = released.find(b => b.id === e.target.value); setBomId(e.target.value); if (selected) { setProductId(selected.productMaterialId || ''); setProduct(selected.productName); setSku(selected.productSku); } }}><option value="">不关联 BOM</option>{released.filter(b => !productId || b.productMaterialId === productId).map(b => <option key={b.id} value={b.id}>{b.productSku} · {b.productName} · V{b.revision}</option>)}</select></Field><p className="muted">生产产品来自物料档案；关联 BOM 后将计算并保存计划物料需求快照。</p><div className="form-grid"><Field label="计划编号"><input value={code} onChange={e => setCode(e.target.value)} required/></Field><Field label="计划数量（件）"><input type="number" min="1" value={qty} onChange={e => setQty(e.target.value)} required/></Field></div><Field label="截止时间"><input type="datetime-local" value={due} onChange={e => setDue(e.target.value)} required/></Field><Field label="备注"><textarea value={note} onChange={e => setNote(e.target.value)} rows={3}/></Field><Notice error={boms.error || action.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>取消</button><button className="button primary" disabled={action.busy || !productId}>保存计划</button></div></form></Modal>;
}
function PlanDetail({ session }: { session: Session }) {
  const { id } = useParams(); const { data: plan, error, loading, reload } = useLoad<Plan>(id ? `/plans/${id}` : null); const [createOrder, setCreateOrder] = useState(false); const action = useAction(reload);
  if (loading && !plan) return <div className="loading">正在加载…</div>; if (!plan) return <Notice error={error || '计划不存在'}/>;
  const allocated = plan.orders?.reduce((n,o) => n + o.targetQty,0) || 0; const good = plan.orders?.reduce((n,o) => n + o.goodQty,0) || 0;
  return <><Header title={`${plan.code} · ${plan.product}`} subtitle={`SKU ${plan.productSku} · 截止 ${date(plan.dueAt)}`} back="/plans" action={<span className={`badge ${plan.status}`}>{planStatus[plan.status]}</span>}/><Notice error={error || action.error} success={action.success}/><div className="detail-grid"><div><section className="panel"><h2>计划进度</h2><div className="summary-row"><div><span>计划数量</span><strong>{plan.targetQty} 件</strong></div><div><span>已分配工单</span><strong>{allocated} 件</strong></div><div><span>合格完成</span><strong>{good} 件</strong></div></div><Progress done={good} total={plan.targetQty}/>{plan.note && <p>{plan.note}</p>}</section><PlanMaterials plan={plan}/><section className="panel"><div className="panel-head"><h2>关联工单</h2>{plan.status === 'released' && ['admin','planner'].includes(session.user.role) && <button className="text-button" onClick={() => setCreateOrder(true)}><Plus size={16}/>新建工单</button>}</div>{plan.orders?.length ? <div className="record-list">{plan.orders.map(o => <Link to={`/orders/${o.id}`} className="record" key={o.id}><div><strong>{o.code} · {o.operation}</strong><span>操作员 {o.assignee?.name || '—'} · {o.goodQty}/{o.targetQty} 件合格</span></div><span className={`badge ${o.status}`}>{orderStatus[o.status]}</span><ArrowRight size={17}/></Link>)}</div> : <Empty text="计划发布后可创建工单"/>}</section></div><aside className="panel side-panel"><h2>下一步操作</h2>{plan.status === 'draft' && ['admin','planner'].includes(session.user.role) && <button className="button primary full" disabled={action.busy} onClick={() => action.run(`/plans/${plan.id}/release`, { version: plan.version })}>发布计划</button>}{plan.status === 'released' && ['admin','planner'].includes(session.user.role) && <button className="button primary full" onClick={() => setCreateOrder(true)}>创建工单</button>}{plan.status === 'completed' && <p className="muted">计划已完成</p>}</aside></div>{createOrder && <CreateOrder plan={plan} close={() => setCreateOrder(false)} done={() => { setCreateOrder(false); reload(); }}/>}</>;
}
function PlanMaterials({ plan }: { plan: Plan }) {
  return <section className="panel"><h2>物料需求</h2>{plan.bomId ? <><p className="muted">关联 BOM V{plan.bom?.revision}。需求在计划创建时保存，后续 BOM 修订不会改动本计划。</p>{plan.materials?.length ? <div className="record-list">{plan.materials.map(item => <div className="record" key={item.id}><div><strong>{item.componentSku} · {item.componentName}</strong><span>展开后的用量，已计入损耗</span></div><span className="badge">{item.requiredQty} {item.unit}</span></div>)}</div> : <Empty text="BOM 未生成物料需求"/>}</> : <p className="muted">该计划未关联 BOM，可按现有工单流程执行。</p>}</section>;
}
function CreateOrder({ plan, close, done }: { plan: Plan; close: () => void; done: () => void }) {
  const users = useLoad<User[]>('/users'); const [code, setCode] = useState(''); const [operation, setOperation] = useState(''); const [qty, setQty] = useState(''); const [assignee, setAssignee] = useState(''); const action = useAction();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await action.run<Order>(`/plans/${plan.id}/orders`, { code, operation, target_qty: Number(qty), assignee_id: assignee }); if (value) done(); }
  return <Modal title="新建工单" close={close}><form className="form" onSubmit={submit}><div className="form-grid"><Field label="工单编号"><input value={code} onChange={e => setCode(e.target.value)} required/></Field><Field label="工序"><input value={operation} onChange={e => setOperation(e.target.value)} placeholder="例如：组装" required/></Field></div><div className="form-grid"><Field label="计划数量（件）"><input type="number" min="1" max={plan.targetQty} value={qty} onChange={e => setQty(e.target.value)} required/></Field><Field label="操作员"><select value={assignee} onChange={e => setAssignee(e.target.value)} required><option value="">请选择操作员</option>{users.data?.filter(u => u.role === 'operator').map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></Field></div><Notice error={action.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>取消</button><button className="button primary" disabled={action.busy}>下达工单</button></div></form></Modal>;
}
function OrdersPage() {
  const [page,setPage] = useState(1); const { data, error, loading } = useLoad<Page<Order>>(`/orders?page=${page}`);
  return <><Header title="工单"/><section className="panel"><Notice error={error}/>{loading && !data ? <div className="loading">正在加载…</div> : data?.items.length ? <div className="record-list">{data.items.map(o => <Link to={`/orders/${o.id}`} className="record" key={o.id}><div><strong>{o.code} · {o.operation}</strong><span>{o.plan?.product} · {o.assignee?.name} · 合格 {o.goodQty}/{o.targetQty} 件</span></div><span className={`badge ${o.status}`}>{orderStatus[o.status]}</span><ArrowRight size={17}/></Link>)}</div> : <Empty text="暂无工单，请先发布计划并下达工单"/>}</section><Pager page={page} total={data?.total || 0} change={setPage}/></>;
}
function OrderDetail({ session }: { session: Session }) {
  const { id } = useParams(); const { data: order, error, loading, reload } = useLoad<Order>(id ? `/orders/${id}` : null); const [report, setReport] = useState(false);
  if (loading && !order) return <div className="loading">正在加载…</div>; if (!order) return <Notice error={error || '工单不存在'}/>;
  return <><Header title={`${order.code} · ${order.operation}`} subtitle={`${order.plan?.product} · ${order.plan?.productSku || ''}`} back="/orders" action={<span className={`badge ${order.status}`}>{orderStatus[order.status]}</span>}/><Notice error={error}/><div className="detail-grid"><div><section className="panel"><h2>工单进度</h2><div className="summary-row"><div><span>计划数量</span><strong>{order.targetQty} 件</strong></div><div><span>合格数</span><strong>{order.goodQty} 件</strong></div><div><span>不良数</span><strong>{order.defectQty} 件</strong></div></div><Progress done={order.goodQty} total={order.targetQty}/><p className="muted">操作员：{order.assignee?.name}</p></section><section className="panel"><h2>报工记录</h2>{order.reports?.length ? <div className="report-list">{order.reports.map(r => <div className="report-row" key={r.id}><div><strong>合格 {r.goodQty} · 不良 {r.defectQty}</strong><span>{r.reporter?.name} · {date(r.createdAt)}{r.note ? ` · ${r.note}` : ''}{r.reason ? ` · 原因：${r.reason}` : ''}</span></div><span className={`badge ${r.status}`}>{reportStatus[r.status]}</span></div>)}</div> : <Empty text="还没有报工记录"/>}</section></div><aside className="panel side-panel"><h2>下一步操作</h2>{session.user.role === 'operator' && order.status !== 'completed' && <button className="button primary full" onClick={() => setReport(true)}>提交报工</button>}<Link className="button secondary full" to={`/plans/${order.planId}`}>查看生产计划</Link></aside></div>{report && <SubmitReport order={order} close={() => setReport(false)} done={() => { setReport(false); reload(); }}/>}</>;
}
function SubmitReport({ order, close, done }: { order: Order; close: () => void; done: () => void }) {
  const [good, setGood] = useState(''); const [defect, setDefect] = useState('0'); const [note, setNote] = useState(''); const action = useAction();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await action.run<Report>(`/orders/${order.id}/reports`, { good_qty: Number(good), defect_qty: Number(defect), note }); if (value) done(); }
  return <Modal title="提交报工" close={close}><form className="form" onSubmit={submit}><p className="muted">审核通过后计入工单产量，剩余 {order.targetQty - order.goodQty - order.defectQty} 件。</p><div className="form-grid"><Field label="合格数"><input type="number" min="0" value={good} onChange={e => setGood(e.target.value)} required/></Field><Field label="不良数"><input type="number" min="0" value={defect} onChange={e => setDefect(e.target.value)} required/></Field></div><Field label="说明"><textarea rows={3} value={note} onChange={e => setNote(e.target.value)}/></Field><Notice error={action.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>取消</button><button className="button primary" disabled={action.busy || Number(good) + Number(defect) <= 0}>提交审核</button></div></form></Modal>;
}
function ReviewsPage() {
  const { data, error, loading, reload } = useLoad<Report[]>('/reports/pending'); const [reason, setReason] = useState<Record<string,string>>({}); const action = useAction(reload);
  return <><Header title="报工审核"/><Notice error={error || action.error} success={action.success}/><section className="panel">{loading && !data ? <div className="loading">正在加载…</div> : data?.length ? <div className="review-list">{data.map(r => <div className="review-card" key={r.id}><div><strong>{r.order?.code} · {r.order?.operation}</strong><p>{r.reporter?.name} 提交：合格 {r.goodQty} 件，不良 {r.defectQty} 件</p>{r.note && <small>{r.note}</small>}</div><div className="review-actions"><input placeholder="拒绝原因" aria-label="拒绝原因" value={reason[r.id] || ''} onChange={e => setReason({ ...reason, [r.id]: e.target.value })}/><button className="button secondary" disabled={!reason[r.id]?.trim() || action.busy} onClick={() => action.run(`/reports/${r.id}/review`, { decision: 'reject', reason: reason[r.id] })}>拒绝</button><button className="button primary" disabled={action.busy} onClick={() => action.run(`/reports/${r.id}/review`, { decision: 'approve' })}>审核通过</button></div></div>)}</div> : <Empty text="暂无待审核报工"/>}</section></>;
}
