import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { api, roleName, type Session, type User } from './api';
import './member-admin.css';

const roleDetails: Record<string, string> = {
  admin: '管理成员、物料、BOM、计划、工单和审核',
  planner: '维护物料与 BOM，创建生产计划和工单',
  supervisor: '查看车间任务并审核报工',
  operator: '查看指派工单，提交生产报工',
};
const pageSize = 15;

export function MemberAdmin({ session }: { session: Session }) {
  const [members, setMembers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState<'members' | 'roles'>('members'); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [create, setCreate] = useState(false); const [editing, setEditing] = useState<User | null>(null);
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('operator');
  async function refresh() { setMembers(await api<User[]>('/admin/users')); }
  useEffect(() => { refresh().catch(cause => setError(cause instanceof Error ? cause.message : '成员加载失败')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!create && !editing) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setCreate(false); setEditing(null); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [create, editing]);
  async function run(work: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setSuccess(''); try { await work(); await refresh(); setSuccess(message); setCreate(false); setEditing(null); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败'); } finally { setBusy(false); } }
  const filtered = useMemo(() => members.filter(member => `${member.name} ${member.email}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [members, query]);
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  async function add(event: FormEvent) { event.preventDefault(); await run(() => api('/admin/users', { name, email, password, role }), '成员已创建'); }
  async function saveRole(event: FormEvent) { event.preventDefault(); if (!editing || editing.role === role) { setEditing(null); return; } await run(() => api(`/admin/users/${editing.id}`, { role }, 'PATCH'), '角色已更新'); }
  async function toggle(member: User) { const active = !member.active; if (!window.confirm(`${active ? '启用' : '停用'} ${member.name}？${active ? '' : '该成员会退出登录。'}`)) return; await run(() => api(`/admin/users/${member.id}`, { active }, 'PATCH'), active ? '成员已启用' : '成员已停用'); }
  return <div className="member-admin"><div className="page-head"><div className="page-heading"><div><h1>成员管理</h1></div></div></div><div className="member-tabs" role="tablist" aria-label="成员管理"><button role="tab" aria-selected={tab === 'members'} className={tab === 'members' ? 'active' : ''} onClick={() => setTab('members')}>成员</button><button role="tab" aria-selected={tab === 'roles'} className={tab === 'roles' ? 'active' : ''} onClick={() => setTab('roles')}>角色与权限</button></div>
    {error && <div className="notice error" role="alert">{error}</div>}{success && <div className="notice success" role="status">{success}</div>}{loading && <div className="loading">正在加载…</div>}
    {!loading && tab === 'members' && <section className="panel member-panel"><div className="member-panel-head"><div><h2>成员</h2><span>{members.length} 人</span></div><button className="button primary" onClick={() => { setName(''); setEmail(''); setPassword(''); setRole('operator'); setCreate(true); }}>新增成员</button></div><input className="member-search" aria-label="搜索成员" placeholder="搜索姓名或邮箱" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }}/>{visible.length ? <div>{visible.map(member => <div className="member-row" key={member.id}><span className="member-avatar">{member.name.slice(0,1)}</span><div className="member-info"><strong>{member.name}</strong><small>{member.email}</small></div><span className="member-badge">{roleName[member.role]}</span><span className={`member-state ${member.active ? '' : 'inactive'}`}>{member.active ? '在职' : '已停用'}</span><button className="button secondary" onClick={() => { setEditing(member); setRole(member.role); }}>设置角色</button><button className="button secondary" disabled={member.id === session.user.id} onClick={() => toggle(member)}>{member.active ? '停用' : '启用'}</button></div>)}</div> : <div className="member-empty">没有符合条件的成员</div>}{filtered.length > pageSize && <div className="member-pager"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page} / {Math.ceil(filtered.length / pageSize)}</span><button disabled={page * pageSize >= filtered.length} onClick={() => setPage(page + 1)}>下一页</button></div>}</section>}
    {!loading && tab === 'roles' && <section className="panel member-panel"><div className="member-panel-head"><div><h2>角色与权限</h2><span>角色权限由服务端业务规则控制</span></div><button className="button secondary" onClick={() => setTab('members')}>为成员设置角色</button></div><div className="member-role-grid">{Object.entries(roleName).map(([id,label]) => <div key={id}><strong>{label}</strong><p>{roleDetails[id]}</p><span>{members.filter(member => member.active && member.role === id).length} 位在职成员</span></div>)}</div></section>}
    {(create || editing) && <div className="member-overlay" onMouseDown={() => { setCreate(false); setEditing(null); }}><section className="member-dialog" role="dialog" aria-modal="true" aria-label={create ? '新增成员' : '设置角色'} onMouseDown={event => event.stopPropagation()}><div className="member-dialog-head"><h2>{create ? '新增成员' : `设置角色 · ${editing?.name}`}</h2><button type="button" aria-label="关闭" onClick={() => { setCreate(false); setEditing(null); }}>×</button></div><form onSubmit={create ? add : saveRole}>{create && <><label>姓名<input value={name} onChange={event => setName(event.target.value)} required/></label><label>邮箱<input type="email" value={email} onChange={event => setEmail(event.target.value)} required/></label><label>初始密码（至少 12 位）<input type="password" autoComplete="new-password" minLength={12} value={password} onChange={event => setPassword(event.target.value)} required/></label></>}<label>角色<select value={role} onChange={event => setRole(event.target.value)}>{Object.entries(roleName).map(([id,label]) => <option value={id} key={id}>{label}</option>)}</select></label>{editing && <p className="member-hint">修改角色后，该成员需要重新登录。</p>}<div className="member-dialog-actions"><button type="button" className="button secondary" onClick={() => { setCreate(false); setEditing(null); }}>取消</button><button className="button primary" disabled={busy}>{create ? '创建成员' : '保存角色'}</button></div></form></section></div>}
  </div>;
}
